version: '3.9'

services:
  backend:
    build: ./backend
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./storage:/app/storage
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    ports:
      - "5173:5173"
    depends_on:
      - backend
