version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PYTHONPATH: "/app:/etl"
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - postgres
      - minio
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - ./etl:/etl

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - ./shared:/shared

volumes:
  postgres_data:
  minio_data:
